The return of devise-guests gem
Turns out the app does have dependencies on this even though Cline
removed the guests DB table. Without this gem we were getting the
following error for any request to the app:

  Processing by CatalogController#index as HTML
  Completed 500 Internal Server Error in 4ms

  NoMethodError (undefined method `bookmarks' for nil:NilClass):
    lib/blacklight/catalog.rb:40:in `index'