DACCESS-260 - update blacklight and view_component
 1) AdvancedHelper#render_edited_advanced_search boolean_row is missing defaults to selecting the "AND" boolean when boolean_row is missing
     Failure/Error: component: Blacklight::Hierarchy::FacetFieldListComponent,

     NoMethodError:
       undefined method `_sidecar_files' for Blacklight::FacetFieldListComponent:Class
2) AdvancedHelper#render_edited_advanced_search non-default operators and booleans selected pre-fills previously selected values
     Failure/Error: component: Blacklight::Hierarchy::FacetFieldListComponent,

     NoMethodError:
       undefined method `_sidecar_files' for Blacklight::FacetFieldListComponent:Class